PREFIX = str(local(
    "basename $(pwd) | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | tr -s '-' | sed 's/^-//;s/-$//'",
    quiet=True,
)).strip()
PORTLESS_PORT = "1355"
TILT_PORT = os.environ.get("TILT_PORT", "10350")

def free_port():
    return str(local(
        "python3 -c 'import socket; s=socket.socket(); s.bind((\"\",0)); print(s.getsockname()[1]); s.close()'",
        quiet=True,
    )).strip()

WEB_PORT = os.environ.get("WEB_PORT")
if not WEB_PORT:
    WEB_PORT = free_port()
WEB_URL = "https://web.{}.localhost:{}".format(PREFIX, PORTLESS_PORT)
TILT_URL = "https://tilt.{}.localhost:{}".format(PREFIX, PORTLESS_PORT)

local_resource(
    "generate-env",
    cmd="""cat > .env.tilt <<'EOF'
# Auto-generated by Tilt — do not edit
PREFIX={prefix}
WEB_URL={web_url}
TILT_URL={tilt_url}
PORTLESS_PORT={portless_port}
TILT_PORT={tilt_port}
WEB_PORT={web_port}
EOF""".format(
        prefix=PREFIX,
        web_url=WEB_URL,
        tilt_url=TILT_URL,
        portless_port=PORTLESS_PORT,
        tilt_port=TILT_PORT,
        web_port=WEB_PORT,
    ),
    labels=["z_helpers"],
)

local_resource(
    "tilt-ui",
    cmd="portless alias tilt.{} {} --force".format(PREFIX, TILT_PORT),
    labels=["z_helpers"],
    links=[TILT_URL],
)

local_resource(
    "web-alias",
    cmd="portless alias web.{} {} --force".format(PREFIX, WEB_PORT),
    labels=["z_helpers"],
    links=[WEB_URL],
)

local_resource(
    "install",
    cmd="bun install",
    deps=["package.json"],
    labels=["jobs"],
)

local_resource(
    "needle-assets",
    cmd="./scripts/download-needle.sh",
    deps=["scripts/download-needle.sh"],
    resource_deps=["install"],
    labels=["jobs"],
)

local_resource(
    "demo",
    serve_cmd="bunx vite --config demo/vite.config.ts --host 127.0.0.1 --port $PORT --strictPort",
    serve_env={"PORT": WEB_PORT, "PREFIX": PREFIX},
    resource_deps=["install", "needle-assets", "generate-env", "tilt-ui", "web-alias"],
    links=[WEB_URL],
    labels=["app"],
)
